/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TournamentsRouteImport } from './routes/tournaments'
import { Route as PlayersRouteImport } from './routes/players'
import { Route as PlayerRouteImport } from './routes/player'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CoachesRouteImport } from './routes/coaches'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as PlayerWorkoutsRouteImport } from './routes/player.workouts'
import { Route as PlayerTrainingRouteImport } from './routes/player.training'
import { Route as PlayerTournamentsRouteImport } from './routes/player.tournaments'
import { Route as PlayerTacticsRouteImport } from './routes/player.tactics'
import { Route as PlayerSubmissionsRouteImport } from './routes/player.submissions'
import { Route as PlayerStatsRouteImport } from './routes/player.stats'
import { Route as PlayerSettingsRouteImport } from './routes/player.settings'
import { Route as PlayerProfileRouteImport } from './routes/player.profile'
import { Route as PlayerNotificationsRouteImport } from './routes/player.notifications'
import { Route as PlayerInjuryRouteImport } from './routes/player.injury'
import { Route as PlayerFitnessRouteImport } from './routes/player.fitness'
import { Route as PlayerDashboardRouteImport } from './routes/player.dashboard'
import { Route as PlayerAttendanceRouteImport } from './routes/player.attendance'
import { Route as DashboardWorkoutsRouteImport } from './routes/dashboard.workouts'
import { Route as DashboardTrainingRouteImport } from './routes/dashboard.training'
import { Route as DashboardTournamentsRouteImport } from './routes/dashboard.tournaments'
import { Route as DashboardTeamLineupRouteImport } from './routes/dashboard.team-lineup'
import { Route as DashboardTacticalRouteImport } from './routes/dashboard.tactical'
import { Route as DashboardSubmissionsRouteImport } from './routes/dashboard.submissions'
import { Route as DashboardStatsRouteImport } from './routes/dashboard.stats'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardPlayersRouteImport } from './routes/dashboard.players'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard.notifications'
import { Route as DashboardInjuriesRouteImport } from './routes/dashboard.injuries'
import { Route as DashboardGalleryRouteImport } from './routes/dashboard.gallery'
import { Route as DashboardFitnessRouteImport } from './routes/dashboard.fitness'
import { Route as DashboardContentRouteImport } from './routes/dashboard.content'
import { Route as DashboardAttendanceRouteImport } from './routes/dashboard.attendance'
import { Route as DashboardAchievementsRouteImport } from './routes/dashboard.achievements'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as PlayerTacticsTacticalIdRouteImport } from './routes/player.tactics.$tacticalId'
import { Route as DashboardWorkoutsCreateRouteImport } from './routes/dashboard.workouts.create'
import { Route as DashboardWorkoutsWorkoutIdRouteImport } from './routes/dashboard.workouts.$workoutId'
import { Route as DashboardTrainingCreateRouteImport } from './routes/dashboard.training.create'
import { Route as DashboardTrainingTrainingIdRouteImport } from './routes/dashboard.training.$trainingId'
import { Route as DashboardTournamentsCreateRouteImport } from './routes/dashboard.tournaments.create'
import { Route as DashboardTournamentsTournamentIdRouteImport } from './routes/dashboard.tournaments.$tournamentId'
import { Route as DashboardTeamLineupCreateRouteImport } from './routes/dashboard.team-lineup.create'
import { Route as DashboardTacticalCreateRouteImport } from './routes/dashboard.tactical.create'
import { Route as DashboardTacticalTacticalIdRouteImport } from './routes/dashboard.tactical.$tacticalId'
import { Route as DashboardPlayersCreateRouteImport } from './routes/dashboard.players.create'
import { Route as DashboardPlayersPlayerIdRouteImport } from './routes/dashboard.players.$playerId'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DashboardWorkoutsWorkoutIdEditRouteImport } from './routes/dashboard.workouts.$workoutId.edit'
import { Route as DashboardTrainingTrainingIdEditRouteImport } from './routes/dashboard.training.$trainingId.edit'
import { Route as DashboardTournamentsTournamentIdEditRouteImport } from './routes/dashboard.tournaments.$tournamentId.edit'
import { Route as DashboardTacticalTacticalIdEditRouteImport } from './routes/dashboard.tactical.$tacticalId.edit'
import { Route as DashboardPlayersPlayerIdEditRouteImport } from './routes/dashboard.players.$playerId.edit'

const TournamentsRoute = TournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersRoute = PlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerRoute = PlayerRouteImport.update({
  id: '/player',
  path: '/player',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachesRoute = CoachesRouteImport.update({
  id: '/coaches',
  path: '/coaches',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const PlayerWorkoutsRoute = PlayerWorkoutsRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => PlayerRoute,
} as any)
const PlayerTrainingRoute = PlayerTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => PlayerRoute,
} as any)
const PlayerTournamentsRoute = PlayerTournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => PlayerRoute,
} as any)
const PlayerTacticsRoute = PlayerTacticsRouteImport.update({
  id: '/tactics',
  path: '/tactics',
  getParentRoute: () => PlayerRoute,
} as any)
const PlayerSubmissionsRoute = PlayerSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => PlayerRoute,
} as any)
const PlayerStatsRoute = PlayerStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => PlayerRoute,
} as any)
const PlayerSettingsRoute = PlayerSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PlayerRoute,
} as any)
const PlayerProfileRoute = PlayerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PlayerRoute,
} as any)
const PlayerNotificationsRoute = PlayerNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => PlayerRoute,
} as any)
const PlayerInjuryRoute = PlayerInjuryRouteImport.update({
  id: '/injury',
  path: '/injury',
  getParentRoute: () => PlayerRoute,
} as any)
const PlayerFitnessRoute = PlayerFitnessRouteImport.update({
  id: '/fitness',
  path: '/fitness',
  getParentRoute: () => PlayerRoute,
} as any)
const PlayerDashboardRoute = PlayerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PlayerRoute,
} as any)
const PlayerAttendanceRoute = PlayerAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => PlayerRoute,
} as any)
const DashboardWorkoutsRoute = DashboardWorkoutsRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTrainingRoute = DashboardTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTournamentsRoute = DashboardTournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTeamLineupRoute = DashboardTeamLineupRouteImport.update({
  id: '/team-lineup',
  path: '/team-lineup',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTacticalRoute = DashboardTacticalRouteImport.update({
  id: '/tactical',
  path: '/tactical',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSubmissionsRoute = DashboardSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStatsRoute = DashboardStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPlayersRoute = DashboardPlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInjuriesRoute = DashboardInjuriesRouteImport.update({
  id: '/injuries',
  path: '/injuries',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGalleryRoute = DashboardGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFitnessRoute = DashboardFitnessRouteImport.update({
  id: '/fitness',
  path: '/fitness',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardContentRoute = DashboardContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAttendanceRoute = DashboardAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAchievementsRoute = DashboardAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => DashboardRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const PlayerTacticsTacticalIdRoute = PlayerTacticsTacticalIdRouteImport.update({
  id: '/$tacticalId',
  path: '/$tacticalId',
  getParentRoute: () => PlayerTacticsRoute,
} as any)
const DashboardWorkoutsCreateRoute = DashboardWorkoutsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => DashboardWorkoutsRoute,
} as any)
const DashboardWorkoutsWorkoutIdRoute =
  DashboardWorkoutsWorkoutIdRouteImport.update({
    id: '/$workoutId',
    path: '/$workoutId',
    getParentRoute: () => DashboardWorkoutsRoute,
  } as any)
const DashboardTrainingCreateRoute = DashboardTrainingCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => DashboardTrainingRoute,
} as any)
const DashboardTrainingTrainingIdRoute =
  DashboardTrainingTrainingIdRouteImport.update({
    id: '/$trainingId',
    path: '/$trainingId',
    getParentRoute: () => DashboardTrainingRoute,
  } as any)
const DashboardTournamentsCreateRoute =
  DashboardTournamentsCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => DashboardTournamentsRoute,
  } as any)
const DashboardTournamentsTournamentIdRoute =
  DashboardTournamentsTournamentIdRouteImport.update({
    id: '/$tournamentId',
    path: '/$tournamentId',
    getParentRoute: () => DashboardTournamentsRoute,
  } as any)
const DashboardTeamLineupCreateRoute =
  DashboardTeamLineupCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => DashboardTeamLineupRoute,
  } as any)
const DashboardTacticalCreateRoute = DashboardTacticalCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => DashboardTacticalRoute,
} as any)
const DashboardTacticalTacticalIdRoute =
  DashboardTacticalTacticalIdRouteImport.update({
    id: '/$tacticalId',
    path: '/$tacticalId',
    getParentRoute: () => DashboardTacticalRoute,
  } as any)
const DashboardPlayersCreateRoute = DashboardPlayersCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => DashboardPlayersRoute,
} as any)
const DashboardPlayersPlayerIdRoute =
  DashboardPlayersPlayerIdRouteImport.update({
    id: '/$playerId',
    path: '/$playerId',
    getParentRoute: () => DashboardPlayersRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardWorkoutsWorkoutIdEditRoute =
  DashboardWorkoutsWorkoutIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => DashboardWorkoutsWorkoutIdRoute,
  } as any)
const DashboardTrainingTrainingIdEditRoute =
  DashboardTrainingTrainingIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => DashboardTrainingTrainingIdRoute,
  } as any)
const DashboardTournamentsTournamentIdEditRoute =
  DashboardTournamentsTournamentIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => DashboardTournamentsTournamentIdRoute,
  } as any)
const DashboardTacticalTacticalIdEditRoute =
  DashboardTacticalTacticalIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => DashboardTacticalTacticalIdRoute,
  } as any)
const DashboardPlayersPlayerIdEditRoute =
  DashboardPlayersPlayerIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => DashboardPlayersPlayerIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/coaches': typeof CoachesRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/player': typeof PlayerRouteWithChildren
  '/players': typeof PlayersRoute
  '/tournaments': typeof TournamentsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/dashboard/achievements': typeof DashboardAchievementsRoute
  '/dashboard/attendance': typeof DashboardAttendanceRoute
  '/dashboard/content': typeof DashboardContentRoute
  '/dashboard/fitness': typeof DashboardFitnessRoute
  '/dashboard/gallery': typeof DashboardGalleryRoute
  '/dashboard/injuries': typeof DashboardInjuriesRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/players': typeof DashboardPlayersRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/stats': typeof DashboardStatsRoute
  '/dashboard/submissions': typeof DashboardSubmissionsRoute
  '/dashboard/tactical': typeof DashboardTacticalRouteWithChildren
  '/dashboard/team-lineup': typeof DashboardTeamLineupRouteWithChildren
  '/dashboard/tournaments': typeof DashboardTournamentsRouteWithChildren
  '/dashboard/training': typeof DashboardTrainingRouteWithChildren
  '/dashboard/workouts': typeof DashboardWorkoutsRouteWithChildren
  '/player/attendance': typeof PlayerAttendanceRoute
  '/player/dashboard': typeof PlayerDashboardRoute
  '/player/fitness': typeof PlayerFitnessRoute
  '/player/injury': typeof PlayerInjuryRoute
  '/player/notifications': typeof PlayerNotificationsRoute
  '/player/profile': typeof PlayerProfileRoute
  '/player/settings': typeof PlayerSettingsRoute
  '/player/stats': typeof PlayerStatsRoute
  '/player/submissions': typeof PlayerSubmissionsRoute
  '/player/tactics': typeof PlayerTacticsRouteWithChildren
  '/player/tournaments': typeof PlayerTournamentsRoute
  '/player/training': typeof PlayerTrainingRoute
  '/player/workouts': typeof PlayerWorkoutsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/dashboard/players/$playerId': typeof DashboardPlayersPlayerIdRouteWithChildren
  '/dashboard/players/create': typeof DashboardPlayersCreateRoute
  '/dashboard/tactical/$tacticalId': typeof DashboardTacticalTacticalIdRouteWithChildren
  '/dashboard/tactical/create': typeof DashboardTacticalCreateRoute
  '/dashboard/team-lineup/create': typeof DashboardTeamLineupCreateRoute
  '/dashboard/tournaments/$tournamentId': typeof DashboardTournamentsTournamentIdRouteWithChildren
  '/dashboard/tournaments/create': typeof DashboardTournamentsCreateRoute
  '/dashboard/training/$trainingId': typeof DashboardTrainingTrainingIdRouteWithChildren
  '/dashboard/training/create': typeof DashboardTrainingCreateRoute
  '/dashboard/workouts/$workoutId': typeof DashboardWorkoutsWorkoutIdRouteWithChildren
  '/dashboard/workouts/create': typeof DashboardWorkoutsCreateRoute
  '/player/tactics/$tacticalId': typeof PlayerTacticsTacticalIdRoute
  '/dashboard/players/$playerId/edit': typeof DashboardPlayersPlayerIdEditRoute
  '/dashboard/tactical/$tacticalId/edit': typeof DashboardTacticalTacticalIdEditRoute
  '/dashboard/tournaments/$tournamentId/edit': typeof DashboardTournamentsTournamentIdEditRoute
  '/dashboard/training/$trainingId/edit': typeof DashboardTrainingTrainingIdEditRoute
  '/dashboard/workouts/$workoutId/edit': typeof DashboardWorkoutsWorkoutIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/coaches': typeof CoachesRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/player': typeof PlayerRouteWithChildren
  '/players': typeof PlayersRoute
  '/tournaments': typeof TournamentsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/dashboard/achievements': typeof DashboardAchievementsRoute
  '/dashboard/attendance': typeof DashboardAttendanceRoute
  '/dashboard/content': typeof DashboardContentRoute
  '/dashboard/fitness': typeof DashboardFitnessRoute
  '/dashboard/gallery': typeof DashboardGalleryRoute
  '/dashboard/injuries': typeof DashboardInjuriesRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/players': typeof DashboardPlayersRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/stats': typeof DashboardStatsRoute
  '/dashboard/submissions': typeof DashboardSubmissionsRoute
  '/dashboard/tactical': typeof DashboardTacticalRouteWithChildren
  '/dashboard/team-lineup': typeof DashboardTeamLineupRouteWithChildren
  '/dashboard/tournaments': typeof DashboardTournamentsRouteWithChildren
  '/dashboard/training': typeof DashboardTrainingRouteWithChildren
  '/dashboard/workouts': typeof DashboardWorkoutsRouteWithChildren
  '/player/attendance': typeof PlayerAttendanceRoute
  '/player/dashboard': typeof PlayerDashboardRoute
  '/player/fitness': typeof PlayerFitnessRoute
  '/player/injury': typeof PlayerInjuryRoute
  '/player/notifications': typeof PlayerNotificationsRoute
  '/player/profile': typeof PlayerProfileRoute
  '/player/settings': typeof PlayerSettingsRoute
  '/player/stats': typeof PlayerStatsRoute
  '/player/submissions': typeof PlayerSubmissionsRoute
  '/player/tactics': typeof PlayerTacticsRouteWithChildren
  '/player/tournaments': typeof PlayerTournamentsRoute
  '/player/training': typeof PlayerTrainingRoute
  '/player/workouts': typeof PlayerWorkoutsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/dashboard/players/$playerId': typeof DashboardPlayersPlayerIdRouteWithChildren
  '/dashboard/players/create': typeof DashboardPlayersCreateRoute
  '/dashboard/tactical/$tacticalId': typeof DashboardTacticalTacticalIdRouteWithChildren
  '/dashboard/tactical/create': typeof DashboardTacticalCreateRoute
  '/dashboard/team-lineup/create': typeof DashboardTeamLineupCreateRoute
  '/dashboard/tournaments/$tournamentId': typeof DashboardTournamentsTournamentIdRouteWithChildren
  '/dashboard/tournaments/create': typeof DashboardTournamentsCreateRoute
  '/dashboard/training/$trainingId': typeof DashboardTrainingTrainingIdRouteWithChildren
  '/dashboard/training/create': typeof DashboardTrainingCreateRoute
  '/dashboard/workouts/$workoutId': typeof DashboardWorkoutsWorkoutIdRouteWithChildren
  '/dashboard/workouts/create': typeof DashboardWorkoutsCreateRoute
  '/player/tactics/$tacticalId': typeof PlayerTacticsTacticalIdRoute
  '/dashboard/players/$playerId/edit': typeof DashboardPlayersPlayerIdEditRoute
  '/dashboard/tactical/$tacticalId/edit': typeof DashboardTacticalTacticalIdEditRoute
  '/dashboard/tournaments/$tournamentId/edit': typeof DashboardTournamentsTournamentIdEditRoute
  '/dashboard/training/$trainingId/edit': typeof DashboardTrainingTrainingIdEditRoute
  '/dashboard/workouts/$workoutId/edit': typeof DashboardWorkoutsWorkoutIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/coaches': typeof CoachesRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/player': typeof PlayerRouteWithChildren
  '/players': typeof PlayersRoute
  '/tournaments': typeof TournamentsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/dashboard/achievements': typeof DashboardAchievementsRoute
  '/dashboard/attendance': typeof DashboardAttendanceRoute
  '/dashboard/content': typeof DashboardContentRoute
  '/dashboard/fitness': typeof DashboardFitnessRoute
  '/dashboard/gallery': typeof DashboardGalleryRoute
  '/dashboard/injuries': typeof DashboardInjuriesRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/players': typeof DashboardPlayersRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/stats': typeof DashboardStatsRoute
  '/dashboard/submissions': typeof DashboardSubmissionsRoute
  '/dashboard/tactical': typeof DashboardTacticalRouteWithChildren
  '/dashboard/team-lineup': typeof DashboardTeamLineupRouteWithChildren
  '/dashboard/tournaments': typeof DashboardTournamentsRouteWithChildren
  '/dashboard/training': typeof DashboardTrainingRouteWithChildren
  '/dashboard/workouts': typeof DashboardWorkoutsRouteWithChildren
  '/player/attendance': typeof PlayerAttendanceRoute
  '/player/dashboard': typeof PlayerDashboardRoute
  '/player/fitness': typeof PlayerFitnessRoute
  '/player/injury': typeof PlayerInjuryRoute
  '/player/notifications': typeof PlayerNotificationsRoute
  '/player/profile': typeof PlayerProfileRoute
  '/player/settings': typeof PlayerSettingsRoute
  '/player/stats': typeof PlayerStatsRoute
  '/player/submissions': typeof PlayerSubmissionsRoute
  '/player/tactics': typeof PlayerTacticsRouteWithChildren
  '/player/tournaments': typeof PlayerTournamentsRoute
  '/player/training': typeof PlayerTrainingRoute
  '/player/workouts': typeof PlayerWorkoutsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/dashboard/players/$playerId': typeof DashboardPlayersPlayerIdRouteWithChildren
  '/dashboard/players/create': typeof DashboardPlayersCreateRoute
  '/dashboard/tactical/$tacticalId': typeof DashboardTacticalTacticalIdRouteWithChildren
  '/dashboard/tactical/create': typeof DashboardTacticalCreateRoute
  '/dashboard/team-lineup/create': typeof DashboardTeamLineupCreateRoute
  '/dashboard/tournaments/$tournamentId': typeof DashboardTournamentsTournamentIdRouteWithChildren
  '/dashboard/tournaments/create': typeof DashboardTournamentsCreateRoute
  '/dashboard/training/$trainingId': typeof DashboardTrainingTrainingIdRouteWithChildren
  '/dashboard/training/create': typeof DashboardTrainingCreateRoute
  '/dashboard/workouts/$workoutId': typeof DashboardWorkoutsWorkoutIdRouteWithChildren
  '/dashboard/workouts/create': typeof DashboardWorkoutsCreateRoute
  '/player/tactics/$tacticalId': typeof PlayerTacticsTacticalIdRoute
  '/dashboard/players/$playerId/edit': typeof DashboardPlayersPlayerIdEditRoute
  '/dashboard/tactical/$tacticalId/edit': typeof DashboardTacticalTacticalIdEditRoute
  '/dashboard/tournaments/$tournamentId/edit': typeof DashboardTournamentsTournamentIdEditRoute
  '/dashboard/training/$trainingId/edit': typeof DashboardTrainingTrainingIdEditRoute
  '/dashboard/workouts/$workoutId/edit': typeof DashboardWorkoutsWorkoutIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/achievements'
    | '/coaches'
    | '/contact'
    | '/dashboard'
    | '/gallery'
    | '/login'
    | '/mcp'
    | '/player'
    | '/players'
    | '/tournaments'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/dashboard/achievements'
    | '/dashboard/attendance'
    | '/dashboard/content'
    | '/dashboard/fitness'
    | '/dashboard/gallery'
    | '/dashboard/injuries'
    | '/dashboard/notifications'
    | '/dashboard/players'
    | '/dashboard/settings'
    | '/dashboard/stats'
    | '/dashboard/submissions'
    | '/dashboard/tactical'
    | '/dashboard/team-lineup'
    | '/dashboard/tournaments'
    | '/dashboard/training'
    | '/dashboard/workouts'
    | '/player/attendance'
    | '/player/dashboard'
    | '/player/fitness'
    | '/player/injury'
    | '/player/notifications'
    | '/player/profile'
    | '/player/settings'
    | '/player/stats'
    | '/player/submissions'
    | '/player/tactics'
    | '/player/tournaments'
    | '/player/training'
    | '/player/workouts'
    | '/dashboard/'
    | '/.mcp/invoke-tool/$tool'
    | '/dashboard/players/$playerId'
    | '/dashboard/players/create'
    | '/dashboard/tactical/$tacticalId'
    | '/dashboard/tactical/create'
    | '/dashboard/team-lineup/create'
    | '/dashboard/tournaments/$tournamentId'
    | '/dashboard/tournaments/create'
    | '/dashboard/training/$trainingId'
    | '/dashboard/training/create'
    | '/dashboard/workouts/$workoutId'
    | '/dashboard/workouts/create'
    | '/player/tactics/$tacticalId'
    | '/dashboard/players/$playerId/edit'
    | '/dashboard/tactical/$tacticalId/edit'
    | '/dashboard/tournaments/$tournamentId/edit'
    | '/dashboard/training/$trainingId/edit'
    | '/dashboard/workouts/$workoutId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/achievements'
    | '/coaches'
    | '/contact'
    | '/gallery'
    | '/login'
    | '/mcp'
    | '/player'
    | '/players'
    | '/tournaments'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/dashboard/achievements'
    | '/dashboard/attendance'
    | '/dashboard/content'
    | '/dashboard/fitness'
    | '/dashboard/gallery'
    | '/dashboard/injuries'
    | '/dashboard/notifications'
    | '/dashboard/players'
    | '/dashboard/settings'
    | '/dashboard/stats'
    | '/dashboard/submissions'
    | '/dashboard/tactical'
    | '/dashboard/team-lineup'
    | '/dashboard/tournaments'
    | '/dashboard/training'
    | '/dashboard/workouts'
    | '/player/attendance'
    | '/player/dashboard'
    | '/player/fitness'
    | '/player/injury'
    | '/player/notifications'
    | '/player/profile'
    | '/player/settings'
    | '/player/stats'
    | '/player/submissions'
    | '/player/tactics'
    | '/player/tournaments'
    | '/player/training'
    | '/player/workouts'
    | '/dashboard'
    | '/.mcp/invoke-tool/$tool'
    | '/dashboard/players/$playerId'
    | '/dashboard/players/create'
    | '/dashboard/tactical/$tacticalId'
    | '/dashboard/tactical/create'
    | '/dashboard/team-lineup/create'
    | '/dashboard/tournaments/$tournamentId'
    | '/dashboard/tournaments/create'
    | '/dashboard/training/$trainingId'
    | '/dashboard/training/create'
    | '/dashboard/workouts/$workoutId'
    | '/dashboard/workouts/create'
    | '/player/tactics/$tacticalId'
    | '/dashboard/players/$playerId/edit'
    | '/dashboard/tactical/$tacticalId/edit'
    | '/dashboard/tournaments/$tournamentId/edit'
    | '/dashboard/training/$trainingId/edit'
    | '/dashboard/workouts/$workoutId/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/achievements'
    | '/coaches'
    | '/contact'
    | '/dashboard'
    | '/gallery'
    | '/login'
    | '/mcp'
    | '/player'
    | '/players'
    | '/tournaments'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/dashboard/achievements'
    | '/dashboard/attendance'
    | '/dashboard/content'
    | '/dashboard/fitness'
    | '/dashboard/gallery'
    | '/dashboard/injuries'
    | '/dashboard/notifications'
    | '/dashboard/players'
    | '/dashboard/settings'
    | '/dashboard/stats'
    | '/dashboard/submissions'
    | '/dashboard/tactical'
    | '/dashboard/team-lineup'
    | '/dashboard/tournaments'
    | '/dashboard/training'
    | '/dashboard/workouts'
    | '/player/attendance'
    | '/player/dashboard'
    | '/player/fitness'
    | '/player/injury'
    | '/player/notifications'
    | '/player/profile'
    | '/player/settings'
    | '/player/stats'
    | '/player/submissions'
    | '/player/tactics'
    | '/player/tournaments'
    | '/player/training'
    | '/player/workouts'
    | '/dashboard/'
    | '/.mcp/invoke-tool/$tool'
    | '/dashboard/players/$playerId'
    | '/dashboard/players/create'
    | '/dashboard/tactical/$tacticalId'
    | '/dashboard/tactical/create'
    | '/dashboard/team-lineup/create'
    | '/dashboard/tournaments/$tournamentId'
    | '/dashboard/tournaments/create'
    | '/dashboard/training/$trainingId'
    | '/dashboard/training/create'
    | '/dashboard/workouts/$workoutId'
    | '/dashboard/workouts/create'
    | '/player/tactics/$tacticalId'
    | '/dashboard/players/$playerId/edit'
    | '/dashboard/tactical/$tacticalId/edit'
    | '/dashboard/tournaments/$tournamentId/edit'
    | '/dashboard/training/$trainingId/edit'
    | '/dashboard/workouts/$workoutId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AchievementsRoute: typeof AchievementsRoute
  CoachesRoute: typeof CoachesRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  GalleryRoute: typeof GalleryRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  PlayerRoute: typeof PlayerRouteWithChildren
  PlayersRoute: typeof PlayersRoute
  TournamentsRoute: typeof TournamentsRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tournaments': {
      id: '/tournaments'
      path: '/tournaments'
      fullPath: '/tournaments'
      preLoaderRoute: typeof TournamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players': {
      id: '/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player': {
      id: '/player'
      path: '/player'
      fullPath: '/player'
      preLoaderRoute: typeof PlayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coaches': {
      id: '/coaches'
      path: '/coaches'
      fullPath: '/coaches'
      preLoaderRoute: typeof CoachesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/player/workouts': {
      id: '/player/workouts'
      path: '/workouts'
      fullPath: '/player/workouts'
      preLoaderRoute: typeof PlayerWorkoutsRouteImport
      parentRoute: typeof PlayerRoute
    }
    '/player/training': {
      id: '/player/training'
      path: '/training'
      fullPath: '/player/training'
      preLoaderRoute: typeof PlayerTrainingRouteImport
      parentRoute: typeof PlayerRoute
    }
    '/player/tournaments': {
      id: '/player/tournaments'
      path: '/tournaments'
      fullPath: '/player/tournaments'
      preLoaderRoute: typeof PlayerTournamentsRouteImport
      parentRoute: typeof PlayerRoute
    }
    '/player/tactics': {
      id: '/player/tactics'
      path: '/tactics'
      fullPath: '/player/tactics'
      preLoaderRoute: typeof PlayerTacticsRouteImport
      parentRoute: typeof PlayerRoute
    }
    '/player/submissions': {
      id: '/player/submissions'
      path: '/submissions'
      fullPath: '/player/submissions'
      preLoaderRoute: typeof PlayerSubmissionsRouteImport
      parentRoute: typeof PlayerRoute
    }
    '/player/stats': {
      id: '/player/stats'
      path: '/stats'
      fullPath: '/player/stats'
      preLoaderRoute: typeof PlayerStatsRouteImport
      parentRoute: typeof PlayerRoute
    }
    '/player/settings': {
      id: '/player/settings'
      path: '/settings'
      fullPath: '/player/settings'
      preLoaderRoute: typeof PlayerSettingsRouteImport
      parentRoute: typeof PlayerRoute
    }
    '/player/profile': {
      id: '/player/profile'
      path: '/profile'
      fullPath: '/player/profile'
      preLoaderRoute: typeof PlayerProfileRouteImport
      parentRoute: typeof PlayerRoute
    }
    '/player/notifications': {
      id: '/player/notifications'
      path: '/notifications'
      fullPath: '/player/notifications'
      preLoaderRoute: typeof PlayerNotificationsRouteImport
      parentRoute: typeof PlayerRoute
    }
    '/player/injury': {
      id: '/player/injury'
      path: '/injury'
      fullPath: '/player/injury'
      preLoaderRoute: typeof PlayerInjuryRouteImport
      parentRoute: typeof PlayerRoute
    }
    '/player/fitness': {
      id: '/player/fitness'
      path: '/fitness'
      fullPath: '/player/fitness'
      preLoaderRoute: typeof PlayerFitnessRouteImport
      parentRoute: typeof PlayerRoute
    }
    '/player/dashboard': {
      id: '/player/dashboard'
      path: '/dashboard'
      fullPath: '/player/dashboard'
      preLoaderRoute: typeof PlayerDashboardRouteImport
      parentRoute: typeof PlayerRoute
    }
    '/player/attendance': {
      id: '/player/attendance'
      path: '/attendance'
      fullPath: '/player/attendance'
      preLoaderRoute: typeof PlayerAttendanceRouteImport
      parentRoute: typeof PlayerRoute
    }
    '/dashboard/workouts': {
      id: '/dashboard/workouts'
      path: '/workouts'
      fullPath: '/dashboard/workouts'
      preLoaderRoute: typeof DashboardWorkoutsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/training': {
      id: '/dashboard/training'
      path: '/training'
      fullPath: '/dashboard/training'
      preLoaderRoute: typeof DashboardTrainingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tournaments': {
      id: '/dashboard/tournaments'
      path: '/tournaments'
      fullPath: '/dashboard/tournaments'
      preLoaderRoute: typeof DashboardTournamentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/team-lineup': {
      id: '/dashboard/team-lineup'
      path: '/team-lineup'
      fullPath: '/dashboard/team-lineup'
      preLoaderRoute: typeof DashboardTeamLineupRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tactical': {
      id: '/dashboard/tactical'
      path: '/tactical'
      fullPath: '/dashboard/tactical'
      preLoaderRoute: typeof DashboardTacticalRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/submissions': {
      id: '/dashboard/submissions'
      path: '/submissions'
      fullPath: '/dashboard/submissions'
      preLoaderRoute: typeof DashboardSubmissionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/stats': {
      id: '/dashboard/stats'
      path: '/stats'
      fullPath: '/dashboard/stats'
      preLoaderRoute: typeof DashboardStatsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/players': {
      id: '/dashboard/players'
      path: '/players'
      fullPath: '/dashboard/players'
      preLoaderRoute: typeof DashboardPlayersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/injuries': {
      id: '/dashboard/injuries'
      path: '/injuries'
      fullPath: '/dashboard/injuries'
      preLoaderRoute: typeof DashboardInjuriesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/gallery': {
      id: '/dashboard/gallery'
      path: '/gallery'
      fullPath: '/dashboard/gallery'
      preLoaderRoute: typeof DashboardGalleryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/fitness': {
      id: '/dashboard/fitness'
      path: '/fitness'
      fullPath: '/dashboard/fitness'
      preLoaderRoute: typeof DashboardFitnessRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/content': {
      id: '/dashboard/content'
      path: '/content'
      fullPath: '/dashboard/content'
      preLoaderRoute: typeof DashboardContentRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/attendance': {
      id: '/dashboard/attendance'
      path: '/attendance'
      fullPath: '/dashboard/attendance'
      preLoaderRoute: typeof DashboardAttendanceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/achievements': {
      id: '/dashboard/achievements'
      path: '/achievements'
      fullPath: '/dashboard/achievements'
      preLoaderRoute: typeof DashboardAchievementsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/tactics/$tacticalId': {
      id: '/player/tactics/$tacticalId'
      path: '/$tacticalId'
      fullPath: '/player/tactics/$tacticalId'
      preLoaderRoute: typeof PlayerTacticsTacticalIdRouteImport
      parentRoute: typeof PlayerTacticsRoute
    }
    '/dashboard/workouts/create': {
      id: '/dashboard/workouts/create'
      path: '/create'
      fullPath: '/dashboard/workouts/create'
      preLoaderRoute: typeof DashboardWorkoutsCreateRouteImport
      parentRoute: typeof DashboardWorkoutsRoute
    }
    '/dashboard/workouts/$workoutId': {
      id: '/dashboard/workouts/$workoutId'
      path: '/$workoutId'
      fullPath: '/dashboard/workouts/$workoutId'
      preLoaderRoute: typeof DashboardWorkoutsWorkoutIdRouteImport
      parentRoute: typeof DashboardWorkoutsRoute
    }
    '/dashboard/training/create': {
      id: '/dashboard/training/create'
      path: '/create'
      fullPath: '/dashboard/training/create'
      preLoaderRoute: typeof DashboardTrainingCreateRouteImport
      parentRoute: typeof DashboardTrainingRoute
    }
    '/dashboard/training/$trainingId': {
      id: '/dashboard/training/$trainingId'
      path: '/$trainingId'
      fullPath: '/dashboard/training/$trainingId'
      preLoaderRoute: typeof DashboardTrainingTrainingIdRouteImport
      parentRoute: typeof DashboardTrainingRoute
    }
    '/dashboard/tournaments/create': {
      id: '/dashboard/tournaments/create'
      path: '/create'
      fullPath: '/dashboard/tournaments/create'
      preLoaderRoute: typeof DashboardTournamentsCreateRouteImport
      parentRoute: typeof DashboardTournamentsRoute
    }
    '/dashboard/tournaments/$tournamentId': {
      id: '/dashboard/tournaments/$tournamentId'
      path: '/$tournamentId'
      fullPath: '/dashboard/tournaments/$tournamentId'
      preLoaderRoute: typeof DashboardTournamentsTournamentIdRouteImport
      parentRoute: typeof DashboardTournamentsRoute
    }
    '/dashboard/team-lineup/create': {
      id: '/dashboard/team-lineup/create'
      path: '/create'
      fullPath: '/dashboard/team-lineup/create'
      preLoaderRoute: typeof DashboardTeamLineupCreateRouteImport
      parentRoute: typeof DashboardTeamLineupRoute
    }
    '/dashboard/tactical/create': {
      id: '/dashboard/tactical/create'
      path: '/create'
      fullPath: '/dashboard/tactical/create'
      preLoaderRoute: typeof DashboardTacticalCreateRouteImport
      parentRoute: typeof DashboardTacticalRoute
    }
    '/dashboard/tactical/$tacticalId': {
      id: '/dashboard/tactical/$tacticalId'
      path: '/$tacticalId'
      fullPath: '/dashboard/tactical/$tacticalId'
      preLoaderRoute: typeof DashboardTacticalTacticalIdRouteImport
      parentRoute: typeof DashboardTacticalRoute
    }
    '/dashboard/players/create': {
      id: '/dashboard/players/create'
      path: '/create'
      fullPath: '/dashboard/players/create'
      preLoaderRoute: typeof DashboardPlayersCreateRouteImport
      parentRoute: typeof DashboardPlayersRoute
    }
    '/dashboard/players/$playerId': {
      id: '/dashboard/players/$playerId'
      path: '/$playerId'
      fullPath: '/dashboard/players/$playerId'
      preLoaderRoute: typeof DashboardPlayersPlayerIdRouteImport
      parentRoute: typeof DashboardPlayersRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/workouts/$workoutId/edit': {
      id: '/dashboard/workouts/$workoutId/edit'
      path: '/edit'
      fullPath: '/dashboard/workouts/$workoutId/edit'
      preLoaderRoute: typeof DashboardWorkoutsWorkoutIdEditRouteImport
      parentRoute: typeof DashboardWorkoutsWorkoutIdRoute
    }
    '/dashboard/training/$trainingId/edit': {
      id: '/dashboard/training/$trainingId/edit'
      path: '/edit'
      fullPath: '/dashboard/training/$trainingId/edit'
      preLoaderRoute: typeof DashboardTrainingTrainingIdEditRouteImport
      parentRoute: typeof DashboardTrainingTrainingIdRoute
    }
    '/dashboard/tournaments/$tournamentId/edit': {
      id: '/dashboard/tournaments/$tournamentId/edit'
      path: '/edit'
      fullPath: '/dashboard/tournaments/$tournamentId/edit'
      preLoaderRoute: typeof DashboardTournamentsTournamentIdEditRouteImport
      parentRoute: typeof DashboardTournamentsTournamentIdRoute
    }
    '/dashboard/tactical/$tacticalId/edit': {
      id: '/dashboard/tactical/$tacticalId/edit'
      path: '/edit'
      fullPath: '/dashboard/tactical/$tacticalId/edit'
      preLoaderRoute: typeof DashboardTacticalTacticalIdEditRouteImport
      parentRoute: typeof DashboardTacticalTacticalIdRoute
    }
    '/dashboard/players/$playerId/edit': {
      id: '/dashboard/players/$playerId/edit'
      path: '/edit'
      fullPath: '/dashboard/players/$playerId/edit'
      preLoaderRoute: typeof DashboardPlayersPlayerIdEditRouteImport
      parentRoute: typeof DashboardPlayersPlayerIdRoute
    }
  }
}

interface DashboardPlayersPlayerIdRouteChildren {
  DashboardPlayersPlayerIdEditRoute: typeof DashboardPlayersPlayerIdEditRoute
}

const DashboardPlayersPlayerIdRouteChildren: DashboardPlayersPlayerIdRouteChildren =
  {
    DashboardPlayersPlayerIdEditRoute: DashboardPlayersPlayerIdEditRoute,
  }

const DashboardPlayersPlayerIdRouteWithChildren =
  DashboardPlayersPlayerIdRoute._addFileChildren(
    DashboardPlayersPlayerIdRouteChildren,
  )

interface DashboardPlayersRouteChildren {
  DashboardPlayersPlayerIdRoute: typeof DashboardPlayersPlayerIdRouteWithChildren
  DashboardPlayersCreateRoute: typeof DashboardPlayersCreateRoute
}

const DashboardPlayersRouteChildren: DashboardPlayersRouteChildren = {
  DashboardPlayersPlayerIdRoute: DashboardPlayersPlayerIdRouteWithChildren,
  DashboardPlayersCreateRoute: DashboardPlayersCreateRoute,
}

const DashboardPlayersRouteWithChildren =
  DashboardPlayersRoute._addFileChildren(DashboardPlayersRouteChildren)

interface DashboardTacticalTacticalIdRouteChildren {
  DashboardTacticalTacticalIdEditRoute: typeof DashboardTacticalTacticalIdEditRoute
}

const DashboardTacticalTacticalIdRouteChildren: DashboardTacticalTacticalIdRouteChildren =
  {
    DashboardTacticalTacticalIdEditRoute: DashboardTacticalTacticalIdEditRoute,
  }

const DashboardTacticalTacticalIdRouteWithChildren =
  DashboardTacticalTacticalIdRoute._addFileChildren(
    DashboardTacticalTacticalIdRouteChildren,
  )

interface DashboardTacticalRouteChildren {
  DashboardTacticalTacticalIdRoute: typeof DashboardTacticalTacticalIdRouteWithChildren
  DashboardTacticalCreateRoute: typeof DashboardTacticalCreateRoute
}

const DashboardTacticalRouteChildren: DashboardTacticalRouteChildren = {
  DashboardTacticalTacticalIdRoute:
    DashboardTacticalTacticalIdRouteWithChildren,
  DashboardTacticalCreateRoute: DashboardTacticalCreateRoute,
}

const DashboardTacticalRouteWithChildren =
  DashboardTacticalRoute._addFileChildren(DashboardTacticalRouteChildren)

interface DashboardTeamLineupRouteChildren {
  DashboardTeamLineupCreateRoute: typeof DashboardTeamLineupCreateRoute
}

const DashboardTeamLineupRouteChildren: DashboardTeamLineupRouteChildren = {
  DashboardTeamLineupCreateRoute: DashboardTeamLineupCreateRoute,
}

const DashboardTeamLineupRouteWithChildren =
  DashboardTeamLineupRoute._addFileChildren(DashboardTeamLineupRouteChildren)

interface DashboardTournamentsTournamentIdRouteChildren {
  DashboardTournamentsTournamentIdEditRoute: typeof DashboardTournamentsTournamentIdEditRoute
}

const DashboardTournamentsTournamentIdRouteChildren: DashboardTournamentsTournamentIdRouteChildren =
  {
    DashboardTournamentsTournamentIdEditRoute:
      DashboardTournamentsTournamentIdEditRoute,
  }

const DashboardTournamentsTournamentIdRouteWithChildren =
  DashboardTournamentsTournamentIdRoute._addFileChildren(
    DashboardTournamentsTournamentIdRouteChildren,
  )

interface DashboardTournamentsRouteChildren {
  DashboardTournamentsTournamentIdRoute: typeof DashboardTournamentsTournamentIdRouteWithChildren
  DashboardTournamentsCreateRoute: typeof DashboardTournamentsCreateRoute
}

const DashboardTournamentsRouteChildren: DashboardTournamentsRouteChildren = {
  DashboardTournamentsTournamentIdRoute:
    DashboardTournamentsTournamentIdRouteWithChildren,
  DashboardTournamentsCreateRoute: DashboardTournamentsCreateRoute,
}

const DashboardTournamentsRouteWithChildren =
  DashboardTournamentsRoute._addFileChildren(DashboardTournamentsRouteChildren)

interface DashboardTrainingTrainingIdRouteChildren {
  DashboardTrainingTrainingIdEditRoute: typeof DashboardTrainingTrainingIdEditRoute
}

const DashboardTrainingTrainingIdRouteChildren: DashboardTrainingTrainingIdRouteChildren =
  {
    DashboardTrainingTrainingIdEditRoute: DashboardTrainingTrainingIdEditRoute,
  }

const DashboardTrainingTrainingIdRouteWithChildren =
  DashboardTrainingTrainingIdRoute._addFileChildren(
    DashboardTrainingTrainingIdRouteChildren,
  )

interface DashboardTrainingRouteChildren {
  DashboardTrainingTrainingIdRoute: typeof DashboardTrainingTrainingIdRouteWithChildren
  DashboardTrainingCreateRoute: typeof DashboardTrainingCreateRoute
}

const DashboardTrainingRouteChildren: DashboardTrainingRouteChildren = {
  DashboardTrainingTrainingIdRoute:
    DashboardTrainingTrainingIdRouteWithChildren,
  DashboardTrainingCreateRoute: DashboardTrainingCreateRoute,
}

const DashboardTrainingRouteWithChildren =
  DashboardTrainingRoute._addFileChildren(DashboardTrainingRouteChildren)

interface DashboardWorkoutsWorkoutIdRouteChildren {
  DashboardWorkoutsWorkoutIdEditRoute: typeof DashboardWorkoutsWorkoutIdEditRoute
}

const DashboardWorkoutsWorkoutIdRouteChildren: DashboardWorkoutsWorkoutIdRouteChildren =
  {
    DashboardWorkoutsWorkoutIdEditRoute: DashboardWorkoutsWorkoutIdEditRoute,
  }

const DashboardWorkoutsWorkoutIdRouteWithChildren =
  DashboardWorkoutsWorkoutIdRoute._addFileChildren(
    DashboardWorkoutsWorkoutIdRouteChildren,
  )

interface DashboardWorkoutsRouteChildren {
  DashboardWorkoutsWorkoutIdRoute: typeof DashboardWorkoutsWorkoutIdRouteWithChildren
  DashboardWorkoutsCreateRoute: typeof DashboardWorkoutsCreateRoute
}

const DashboardWorkoutsRouteChildren: DashboardWorkoutsRouteChildren = {
  DashboardWorkoutsWorkoutIdRoute: DashboardWorkoutsWorkoutIdRouteWithChildren,
  DashboardWorkoutsCreateRoute: DashboardWorkoutsCreateRoute,
}

const DashboardWorkoutsRouteWithChildren =
  DashboardWorkoutsRoute._addFileChildren(DashboardWorkoutsRouteChildren)

interface DashboardRouteChildren {
  DashboardAchievementsRoute: typeof DashboardAchievementsRoute
  DashboardAttendanceRoute: typeof DashboardAttendanceRoute
  DashboardContentRoute: typeof DashboardContentRoute
  DashboardFitnessRoute: typeof DashboardFitnessRoute
  DashboardGalleryRoute: typeof DashboardGalleryRoute
  DashboardInjuriesRoute: typeof DashboardInjuriesRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardPlayersRoute: typeof DashboardPlayersRouteWithChildren
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardStatsRoute: typeof DashboardStatsRoute
  DashboardSubmissionsRoute: typeof DashboardSubmissionsRoute
  DashboardTacticalRoute: typeof DashboardTacticalRouteWithChildren
  DashboardTeamLineupRoute: typeof DashboardTeamLineupRouteWithChildren
  DashboardTournamentsRoute: typeof DashboardTournamentsRouteWithChildren
  DashboardTrainingRoute: typeof DashboardTrainingRouteWithChildren
  DashboardWorkoutsRoute: typeof DashboardWorkoutsRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAchievementsRoute: DashboardAchievementsRoute,
  DashboardAttendanceRoute: DashboardAttendanceRoute,
  DashboardContentRoute: DashboardContentRoute,
  DashboardFitnessRoute: DashboardFitnessRoute,
  DashboardGalleryRoute: DashboardGalleryRoute,
  DashboardInjuriesRoute: DashboardInjuriesRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardPlayersRoute: DashboardPlayersRouteWithChildren,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardStatsRoute: DashboardStatsRoute,
  DashboardSubmissionsRoute: DashboardSubmissionsRoute,
  DashboardTacticalRoute: DashboardTacticalRouteWithChildren,
  DashboardTeamLineupRoute: DashboardTeamLineupRouteWithChildren,
  DashboardTournamentsRoute: DashboardTournamentsRouteWithChildren,
  DashboardTrainingRoute: DashboardTrainingRouteWithChildren,
  DashboardWorkoutsRoute: DashboardWorkoutsRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface PlayerTacticsRouteChildren {
  PlayerTacticsTacticalIdRoute: typeof PlayerTacticsTacticalIdRoute
}

const PlayerTacticsRouteChildren: PlayerTacticsRouteChildren = {
  PlayerTacticsTacticalIdRoute: PlayerTacticsTacticalIdRoute,
}

const PlayerTacticsRouteWithChildren = PlayerTacticsRoute._addFileChildren(
  PlayerTacticsRouteChildren,
)

interface PlayerRouteChildren {
  PlayerAttendanceRoute: typeof PlayerAttendanceRoute
  PlayerDashboardRoute: typeof PlayerDashboardRoute
  PlayerFitnessRoute: typeof PlayerFitnessRoute
  PlayerInjuryRoute: typeof PlayerInjuryRoute
  PlayerNotificationsRoute: typeof PlayerNotificationsRoute
  PlayerProfileRoute: typeof PlayerProfileRoute
  PlayerSettingsRoute: typeof PlayerSettingsRoute
  PlayerStatsRoute: typeof PlayerStatsRoute
  PlayerSubmissionsRoute: typeof PlayerSubmissionsRoute
  PlayerTacticsRoute: typeof PlayerTacticsRouteWithChildren
  PlayerTournamentsRoute: typeof PlayerTournamentsRoute
  PlayerTrainingRoute: typeof PlayerTrainingRoute
  PlayerWorkoutsRoute: typeof PlayerWorkoutsRoute
}

const PlayerRouteChildren: PlayerRouteChildren = {
  PlayerAttendanceRoute: PlayerAttendanceRoute,
  PlayerDashboardRoute: PlayerDashboardRoute,
  PlayerFitnessRoute: PlayerFitnessRoute,
  PlayerInjuryRoute: PlayerInjuryRoute,
  PlayerNotificationsRoute: PlayerNotificationsRoute,
  PlayerProfileRoute: PlayerProfileRoute,
  PlayerSettingsRoute: PlayerSettingsRoute,
  PlayerStatsRoute: PlayerStatsRoute,
  PlayerSubmissionsRoute: PlayerSubmissionsRoute,
  PlayerTacticsRoute: PlayerTacticsRouteWithChildren,
  PlayerTournamentsRoute: PlayerTournamentsRoute,
  PlayerTrainingRoute: PlayerTrainingRoute,
  PlayerWorkoutsRoute: PlayerWorkoutsRoute,
}

const PlayerRouteWithChildren =
  PlayerRoute._addFileChildren(PlayerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AchievementsRoute: AchievementsRoute,
  CoachesRoute: CoachesRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  GalleryRoute: GalleryRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  PlayerRoute: PlayerRouteWithChildren,
  PlayersRoute: PlayersRoute,
  TournamentsRoute: TournamentsRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
